num1=int(input("enter a number: "))
num2=int(input("enter another number: "))
print("Bitwise AND:",num1 & num2)
print("Bitwise OR:",num1 | num2)
print("Bitwise NOT num1:",~num1)
print("Bitwise NOT num2:",~num2)
print("Bitwise XOR:",num1 ^ num2)
print("Bitwise Left Shift num1:",num1 << 2)
print("Bitwise Right Shift num1:",num1 >> 2)
print("Bitwwise Left Shift num2:",num2 << 2)
print("Bitwise Right Shift num2:",num2 >> 2)
print("Bitwise AND  with NOT num1:",num1 & ~num2)