first=int(input("enter one:"))
second=int(input("enter two:"))
print(first+second)
print(first-second)
print(first*second)
print(first%second)
print(first/second)
print(first//second)
print(first**second)