a=int(input("enter a number:"))
b=int(input("enter another number:"))
print("a = ",a," b = ",b)
print("a == b : ",a==b)
print("a != b : ",a!=b)
print("a > b : ",a>b)
print("a < b : ",a<b)
print("a >= b : ",a>=b)
print("a <= b : ",a<=b)