import numpy as np
arr = np.array([[1,2],[3,4]])
arr1 = np.array([[1,2],[3,4]])
print("Addition of two arrays:",arr+arr1)
print("Subtraction of two arrays:",arr-arr1)
print("Multiplication of two arrays:",arr*arr1)
print("Multiplication of two arrays:",arr@arr1)
print("Multiplication of two arrays:",np.matmul(arr,arr1))
print("mean of two arr is :\n",np.mean(arr))
print("Standard Deviation of arr is :\n",np.std(arr))
print("Variance of arr is :\n",np.var(arr))
print("Minimum of  arr is :\n",np.min(arr))
print("Maximum of arr is :\n",np.max(arr))
print("Argmin of arr is :\n",np.argmin(arr))
print("Argmax of arr is :\n",np.argmax(arr))
print("Square root of arr is :\n",np.sqrt(arr))

print("mean of two arr1 is :\n",np.mean(arr1))
print("Standard Deviation of arr1 is :\n",np.std(arr1))
print("Variance of arr1 is :\n",np.var(arr1))
print("Minimum of  arr1 is :\n",np.min(arr1))
print("Maximum of arr1 is :\n",np.max(arr1))
print("Argmin of arr1 is :\n",np.argmin(arr1))
print("Argmax of arr1 is :\n",np.argmax(arr1))
print("Square root of arr1 is :\n",np.sqrt(arr1))