set1 = {1,2,3,4,5}
set2 = {2,4,6,8,0}
print(set1.union(set2))
print(set1.intersection(set2))
print(set1.difference(set2))
print(set1.issubset(set2))
print(set1.issuperset(set2))
set1.pop()
print(set1)
set2.remove(4)
print(set2)
set1.difference_update(set2)
print(set1)
set2.symmetric_difference(set1)
print(set2)
set1.symmetric_difference_update(set2)
print(set1)
set1.intersection_update(set2)
print(set1)
set2.clear()
print(set2)
print(set1.copy())