import pandas as pd
csv_path = "/workspaces/ACE-BOOTCAMP0626/day7/archive (2)/used_car_price_prediction_1M.csv"
df = pd.read_csv(csv_path)
print(df.head(10))
print(df.shape)
print(df.tail(10))
print(df.info())
print(df.iloc[1])
print(df.head())
print(df.loc[0,'Model'])
print(df.loc[:,'Brand']=='BMW')
filt=(df['Brand']=='BMW')
print(df.loc[filt].sort_index(ascending=False).head())
filt=(df['Brand']=='BMW') | (df['Color']=='Blue')
wdf = df.loc[filt].sort_index(ascending=False).tail(50)
print(wdf)
print(type(wdf))
print(df.shape)
print(df['Brand'])
print(df.iloc[0:1,[3, 2]])
