s = set()
for i in range(5):
    s.add(int(input("Enter element: ")))
print("Set:", s)
s.add(int(input("Add: ")))
print(s)
s.update({10, 20})
print(s)
s.remove(int(input("Remove: ")))
print(s)
s.discard(int(input("Discard: ")))
print(s)
print("Popped:", s.pop())
print(s)
print("Union:", s.union({1, 2}))
print("Intersection:", s.intersection({1, 2}))
print("Difference:", s.difference({1, 2}))
print("Length:", len(s))
print("Max:", max(s))
print("Min:", min(s))
print("Sum:", sum(s))
print("After Clear:", s)